FROM caddy:2.7.3-builder AS builder

RUN xcaddy build --with github.com/georgepadayatti/caddy-openapi@v0.8.0

FROM caddy:2.7.3-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

COPY consent-openapi.yaml /consent-openapi.yaml

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]