version: "3.7"

services:

  mongo:
    image: bitnami/mongodb:7.0
    container_name: mongo
    environment:
      - MONGODB_DATABASE=bb-consent-consentdb
      - MONGODB_USERNAME=bb-consent-user
      - MONGODB_PASSWORD=bb-consent-password
      - ALLOW_EMPTY_PASSWORD=yes

  postgresql:
    image: bitnami/postgresql:14.10.0
    container_name: postgresql
    environment:
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_PASSWORD=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak

  keycloak:
    image: docker.io/bitnami/keycloak:22.0.2-debian-11-r0
    container_name: keycloak
    restart: always
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_HOST=postgresql
      - KEYCLOAK_DATABASE_PASSWORD=bn_keycloak
      - KEYCLOAK_HTTP_RELATIVE_PATH=/
      - KEYCLOAK_ENABLE_HTTPS=false
      - KEYCLOAK_ENABLE_STATISTICS=false
      - KEYCLOAK_HTTP_PORT=8080
      - KEYCLOAK_LOG_OUTPUT=default
      - KEYCLOAK_PRODUCTION=false
      - KEYCLOAK_PROXY=edge
    depends_on:
      - postgresql

  api:
    image: igrantio/bb-consent-api:2023.11.15
    container_name: api
    restart: always
    environment:
      - VIRTUAL_HOST=api.bb-consent.dev
    volumes:
      - ./api.json:/opt/bb-consent/api/config/config-production.json:ro
    ports:
      - "3333:80"
    depends_on:
      - mongo
      - keycloak

volumes:
  mongo:
  postgresql:
